# Generated by Django 4.0.6 on 2022-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_blogentry_options_blogentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(default=0, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
