# Generated by Django 2.2 on 2022-06-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_advertisement_cathegory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='cathegory',
            new_name='category',
        ),
    ]
