# Generated by Django 4.0.6 on 2022-08-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('birth_year', models.DateField(verbose_name='birth year')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('isbn', models.IntegerField(max_length=30, verbose_name='isbn')),
                ('year', models.DateField(verbose_name='year')),
                ('pages', models.IntegerField(verbose_name='pages')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_library.author', verbose_name='author')),
            ],
        ),
    ]
