# Generated by Django 4.0.6 on 2022-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='news_published',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
