# Generated by Django 2.2 on 2022-06-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_advertisement_type_of_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
