# Generated by Django 2.2 on 2022-07-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='news_published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
