# Generated by Django 2.2 on 2022-07-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_profile_news_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
