# Generated by Django 2.2 on 2022-07-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_profile_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Может верифицировать'),)},
        ),
    ]
