# Generated by Django 2.2 on 2022-06-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commantary',
            new_name='Commentary',
        ),
    ]
