# Generated by Django 2.2 on 2022-06-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20220629_0828'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
