# Generated by Django 2.2 on 2022-07-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20220701_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='related_news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_news.News', verbose_name='Новость'),
        ),
    ]
