# Generated by Django 2.2 on 2022-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_auto_20220705_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='text',
            field=models.TextField(choices=[('delete', 'Удалено администратором')], max_length=1000, verbose_name='Текст комментария'),
        ),
    ]
